# Generated by Django 5.0.6 on 2024-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('jobType', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], max_length=50)),
                ('appointmentDate', models.DateTimeField()),
                ('technician', models.CharField(max_length=100)),
            ],
        ),
    ]
